name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate syntax
      run: |
        # Add your validation command as
        az  bicep build --file full.bicep
    - name: Deploy to Azure
      run: |
        # Add your deployment command as
         az login
         az deployment group create --resource-group suresh --template-file full.bicep
