name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Validate syntax
        run: |
          npm install -g jsonlint
          jsonlint full.bicep
      - name: Deploy to Azure
        if: success()
        run: |
          az login --service-principal -u ${{ secrets.AZURE_SP_APPID }} -p ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_SP_TENANT }}
          az group create --name suresh --location uksouth
          az deployment group create --resource-group suresh --template-file full.bicep
